### ISSUE TITLE
Tests Failing Out of the Box? Maybe expected, not sure...

### ISSUE THREAD

**Issue by ilan-gold** [scverse/scvi-tools-skeleton#11]
Hi!

I forked the repo and ran the tests locally and then got this error:
https://github.com/ilan-gold/scvi-tools-skeleton/runs/4636399280?check_suite_focus=true

Is this expected?

Ilan

**Comment by ilan-gold** [comment]
Seems I am not alone: #9

**Comment by watiss** [comment]
Hi @ilan-gold . It is expected. We need to complete that PR you linked (# 9) to bring the repo up to speed with the recent breaking changes. We'll do that soon. I'll close this issue once that's done.

**Comment by watiss** [comment]
I pushed some more changes to unblock the pr. @adamgayoso or @jjhong922 if you could take a look when you get a chance.
